# Generated by Django 5.0.6 on 2024-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bonus', models.FloatField(default=None, null=True)),
                ('date_field', models.DateField(default=None, null=True)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'bonus_reward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomCoinRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('no_of_coin', models.IntegerField()),
                ('coin_name', models.CharField(max_length=100)),
                ('create_by', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income2Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('income', models.FloatField()),
                ('levelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Income2Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='INRTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('txnAt', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_txn_id', models.CharField(max_length=100)),
                ('client_txn_id', models.CharField(max_length=15)),
                ('zaan_coin_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversion_usd_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'inr_transaction_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=255)),
                ('otp_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('retry', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendOTP',
            fields=[
                ('Srno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
                ('trxndate', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'send_otp',
                'managed': False,
            },
        ),
    ]
