# Generated by Django 5.0.6 on 2024-06-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zqUsers', '0002_accountcomfirmation_allquestions_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income1',
            table='income1',
        ),
        migrations.AlterModelTable(
            name='income2',
            table='income2',
        ),
        migrations.AlterModelTable(
            name='walletamicoinforuser',
            table='walletamicoin_for_user',
        ),
        migrations.AlterModelTable(
            name='zquser',
            table='zqusers_zquser',
        ),
    ]
